import { Injectable, NgZone, Injector } from '@angular/core';
import { HttpClient, HttpParams, HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Router } from '@angular/router';
import { ApiBase, INITIALIZED_IN_BACKEND, NullableInDraftMode } from '@plano/shared/api/base/api-base';
import { Id } from '@plano/shared/api/base/id';
import { Meta } from '@plano/shared/api/base/meta';
import { ApiAttributeInfo } from '@plano/shared/api/base/api-attribute-info';
import { PApiPrimitiveTypes } from '@plano/shared/api/base/generated-types.ag';
import { ApiSaveArgs, ApiLoadArgs, ShiftId, ShiftSelector, ApiListWrapper, SchedulingApiPosSystem, SchedulingApiBooking, SchedulingApiAccountHolderState, ApiObjectWrapper, AuthenticatedApiRole } from '@plano/shared/api';
import { DateTime, Date, DateExclusiveEnd, LocalTime, Duration, Minutes, Hours, Days, Months, Years, Percent, Email, Search, Tel, Currency, Password, PostalCode, Integer, Url, Iban, Bic, Image } from '@plano/shared/api/base/generated-types.ag';
import { Config } from '@plano/shared/core/config';
import { AbstractControl } from '@angular/forms';
import { ApiErrorService } from '@plano/shared/api/api-error.service';



/**
 * This service enables access to the api "admin/state_machines".
 * This file is auto generated by de.sage.scheduler.api_generator.ApiGenerator.
 */

// constants
class Consts
{
	STATE_MACHINE_DEBUG_INFO = 1;
}


@Injectable({
  providedIn: 'root',
})
export class StateMachinesApiService<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiBase
{
	consts = new Consts();

	constructor(h : HttpClient
			,	router : Router
			,	apiE : ApiErrorService
			,	zone : NgZone
			,	injector : Injector) {
		super(h, router, apiE, zone, injector, 'admin/state_machines');
	}

	protected version() : string {
		return '85bf066e89520378751ea68dabc86232,99bcf972ebf06bc1e7a5abb2ef4fd496';
	}

	private dataWrapper = new StateMachinesApiRoot<ValidationMode>(this, false);

	get data() : StateMachinesApiRoot<ValidationMode> {
		return this.dataWrapper;
	}

	protected getRootWrapper() : StateMachinesApiRoot<ValidationMode> {
		return this.dataWrapper;
	}

	protected recreateRootWrapper() : void {
		this.dataWrapper = new StateMachinesApiRoot<ValidationMode>(this, false);
	}
}

		 export class StateMachinesApiRoot<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiListWrapper<any>
{
	

	constructor(override readonly api : StateMachinesApiService<ValidationMode> | null, removeDestroyedItems : boolean) {
		super(api, removeDestroyedItems, '');
	}

	override wrapItem(item : any, _generateMissingData : boolean) : StateMachinesApiStateMachine<ValidationMode> {
		const newWrapper = new StateMachinesApiStateMachine<ValidationMode>(this.api);
		newWrapper._updateRawData(item, _generateMissingData);
		return newWrapper;
	}

	protected containsPrimitives() : boolean {
		return false;
	}

	protected containsIds() : boolean {
		return false;
	}

	protected createInstance(removeDestroyedItems : boolean) : StateMachinesApiRoot<ValidationMode> {
		return new StateMachinesApiRoot<ValidationMode>(this.api, removeDestroyedItems);
	}

	protected get dni() : string {
		return '1';
	}

	override createNewItem(id : Id | null = null) : StateMachinesApiStateMachine<ValidationMode> {
		const newItemRaw = Meta.createNewObject(false, !!id ? id.rawData : null);

		const newItem = this.wrapItem(newItemRaw, true);
		this.push(newItem);

		if(this.api)
			this.api.changed('');

		return newItem;
	}

	override attributeInfoThis : ApiAttributeInfo<StateMachinesApiRoot<ValidationMode>, StateMachinesApiRoot<ValidationMode>> = new ApiAttributeInfo<StateMachinesApiRoot<ValidationMode>, StateMachinesApiRoot<ValidationMode>>({
			apiObjWrapper: this as any as StateMachinesApiRoot<ValidationMode>,
			name: '',
			id: 'ROOT',
			primitiveType: PApiPrimitiveTypes.ApiList,
			show: function(this : StateMachinesApiRoot<ValidationMode>) {
		if(!(( (this.api!.rightsService.requesterIs(AuthenticatedApiRole.SUPER_ADMIN)) )))
		{
			return false;
		}
				return true;
			},
			canEdit: () => false,
			readMode: () => true,
		});
}

				 
export class StateMachinesApiStateMachine<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiObjectWrapper<any, any>
{
	override parent : any = null;

	constructor(override readonly api : StateMachinesApiService<ValidationMode> | null, idRaw : any = null) {
		super(api, StateMachinesApiStateMachine as any);

		this._updateRawData(Meta.createNewObject(false, idRaw), true);

		// set parent attribute
	}


	private _id : Id | null = null;
	get id() : Id {
		return this._id !== null ? this._id : Id.create(Meta.getNewItemId(this.rawData) as any);
	}

	override attributeInfoThis : ApiAttributeInfo<StateMachinesApiStateMachine<ValidationMode>, StateMachinesApiStateMachine<ValidationMode>> = new ApiAttributeInfo<StateMachinesApiStateMachine<ValidationMode>, StateMachinesApiStateMachine<ValidationMode>>({
			apiObjWrapper: this as any as StateMachinesApiStateMachine<ValidationMode>,
			name: 'stateMachine',
			id: 'STATE_MACHINE',
			canEdit: () => false,
			readMode: () => true,
		});
	attributeInfoDebugInfo =  new ApiAttributeInfo<StateMachinesApiStateMachine<ValidationMode>, any>({
			apiObjWrapper: this as any as StateMachinesApiStateMachine<ValidationMode>,
			name: 'debugInfo',
			id: 'STATE_MACHINE_DEBUG_INFO',
			primitiveType: PApiPrimitiveTypes.any,
			canEdit: () => false,
			readMode: () => true,
		});

	/**
     *  A key value map.
	 *
	 * @type {any}
     */
	get debugInfo() : NullableInDraftMode<any, ValidationMode> {
		return this.data[1];
	}

	set debugInfoTestSetter(v : NullableInDraftMode<any, ValidationMode>) {
        this.setterImpl(1, v, 'debugInfo');
	}


	_fixIds(_idReplacements : Map<any, number>) : void {
	}

	override _updateRawData(data : any[] | null, generateMissingData : boolean) : void {
		super._updateRawData(data, generateMissingData);

		this.data = data;

		// update id wrapper
		const idRawData = Meta.getId(data);
		this._id = idRawData === null ? null : Id.create(idRawData as any);

		// create missing/default data
		if(generateMissingData && data) {
			this.fillWithDefaultValues(data, 2);

		}

		// propagate new raw data to children
	}

	protected get dni() : string {
		return '2';
	}

	static loadDetailed(	api : StateMachinesApiService<any>
						,	id : Id
						,	{success = null, error = null, searchParams = null} : ApiLoadArgs = {}) : Promise<HttpResponse<unknown>> {
		return ApiObjectWrapper.loadDetailedImpl(api, id, '2', { success: success, error: error, searchParams: searchParams});
	}

	protected assumeValidated() : asserts this is StateMachinesApiStateMachine<'validated'> {
		// TODO: PLANO-151346
	}
}



