import { Injectable, NgZone, Injector } from '@angular/core';
import { HttpClient, HttpParams, HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Router } from '@angular/router';
import { ApiBase, INITIALIZED_IN_BACKEND, NullableInDraftMode } from '@plano/shared/api/base/api-base';
import { Id } from '@plano/shared/api/base/id';
import { Meta } from '@plano/shared/api/base/meta';
import { ApiAttributeInfo } from '@plano/shared/api/base/api-attribute-info';
import { PApiPrimitiveTypes } from '@plano/shared/api/base/generated-types.ag';
import { ApiSaveArgs, ApiLoadArgs, ShiftId, ShiftSelector, ApiListWrapper, SchedulingApiPosSystem, SchedulingApiBooking, SchedulingApiAccountHolderState, ApiObjectWrapper, AuthenticatedApiRole } from '@plano/shared/api';
import { DateTime, Date, DateExclusiveEnd, LocalTime, Duration, Minutes, Hours, Days, Months, Years, Percent, Email, Search, Tel, Currency, Password, PostalCode, Integer, Url, Iban, Bic, Image } from '@plano/shared/api/base/generated-types.ag';
import { Config } from '@plano/shared/core/config';
import { AbstractControl } from '@angular/forms';
import { ApiErrorService } from '@plano/shared/api/api-error.service';



/**
 * This service enables access to the api "export_members_excel".
 * This file is auto generated by de.sage.scheduler.api_generator.ApiGenerator.
 */

// constants
class Consts
{
	MEMBER_IDS = 1;
}


@Injectable({
  providedIn: 'root',
})
export class ExportMembersExcelApiService<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiBase
{
	consts = new Consts();

	constructor(h : HttpClient
			,	router : Router
			,	apiE : ApiErrorService
			,	zone : NgZone
			,	injector : Injector) {
		super(h, router, apiE, zone, injector, 'export_members_excel');
	}

	protected version() : string {
		return 'd6f80d754bb1613c558cf697551968e9,6a790456fe8a3fc38a3e0229e53ec677';
	}

	private dataWrapper = new ExportMembersExcelApiRoot<ValidationMode>(this);

	get data() : ExportMembersExcelApiRoot<ValidationMode> {
		return this.dataWrapper;
	}

	protected getRootWrapper() : ExportMembersExcelApiRoot<ValidationMode> {
		return this.dataWrapper;
	}

	protected recreateRootWrapper() : void {
		this.dataWrapper = new ExportMembersExcelApiRoot<ValidationMode>(this);
	}
}

		 
export class ExportMembersExcelApiRoot<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiObjectWrapper<any, any>
{
	

	constructor(override readonly api : ExportMembersExcelApiService<ValidationMode> | null, idRaw : any = null) {
		super(api, ExportMembersExcelApiRoot as any);

		this._updateRawData(Meta.createNewObject(false, idRaw), true);

		// set parent attribute
		this.memberIdsWrapper.parent = this as any as ExportMembersExcelApiRoot<ValidationMode>;
	}


	private _id : Id | null = null;
	get id() : Id {
		return this._id !== null ? this._id : Id.create(Meta.getNewItemId(this.rawData) as any);
	}

	override attributeInfoThis : ApiAttributeInfo<ExportMembersExcelApiRoot<ValidationMode>, ExportMembersExcelApiRoot<ValidationMode>> = new ApiAttributeInfo<ExportMembersExcelApiRoot<ValidationMode>, ExportMembersExcelApiRoot<ValidationMode>>({
			apiObjWrapper: this as any as ExportMembersExcelApiRoot<ValidationMode>,
			name: '',
			id: 'ROOT',
			show: function(this : ExportMembersExcelApiRoot<ValidationMode>) {
		if(!((this.api!.rightsService.hasManagerRights)))
		{
			return false;
		}
				return true;
			},
			canEdit: function(this : ExportMembersExcelApiRoot<ValidationMode>) {
		if(!((this.api!.rightsService.hasManagerRights)))
		{
			return false;
		}
				return true;
			},
			readMode: function(this : ExportMembersExcelApiRoot<ValidationMode>) {
				 
		
				return false;
			},
		});

	private memberIdsWrapper : ExportMembersExcelApiMemberIds<ValidationMode> = new ExportMembersExcelApiMemberIds<ValidationMode>(this.api, false);

	/**
     *  Id list of the members to be exported.
     */
	get memberIds() : ExportMembersExcelApiMemberIds<ValidationMode> {
		return this.memberIdsWrapper;
	}

	set memberIdsTestSetter(v : ExportMembersExcelApiMemberIds<ValidationMode>) {
        this.setterImpl(1, v.rawData, 'memberIds', () => {this.memberIdsWrapper = v;});
	}


	_fixIds(_idReplacements : Map<any, number>) : void {
		this.memberIdsWrapper._fixIds(_idReplacements);
	}

	override _updateRawData(data : any[] | null, generateMissingData : boolean) : void {
		super._updateRawData(data, generateMissingData);

		this.data = data;

		// update id wrapper
		const idRawData = Meta.getId(data);
		this._id = idRawData === null ? null : Id.create(idRawData as any);

		// create missing/default data
		if(generateMissingData && data) {
			this.fillWithDefaultValues(data, 2);

			if(data[1] === null)
				data[1] = Meta.createNewList();
		}

		// propagate new raw data to children
		this.memberIdsWrapper._updateRawData(data ? data[1] : null, generateMissingData);
	}

	protected get dni() : string {
		return '1';
	}

	static loadDetailed(	api : ExportMembersExcelApiService<any>
						,	id : Id
						,	{success = null, error = null, searchParams = null} : ApiLoadArgs = {}) : Promise<HttpResponse<unknown>> {
		return ApiObjectWrapper.loadDetailedImpl(api, id, '1', { success: success, error: error, searchParams: searchParams});
	}

	protected assumeValidated() : asserts this is ExportMembersExcelApiRoot<'validated'> {
		// TODO: PLANO-151346
	}
}

		 export class ExportMembersExcelApiMemberIds<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiListWrapper<any>
{
	override parent : any = null;

	constructor(override readonly api : ExportMembersExcelApiService<ValidationMode> | null, removeDestroyedItems : boolean) {
		super(api, removeDestroyedItems, 'memberIds');
	}

	override wrapItem(item : any, _generateMissingData : boolean) : Id {
		return Id.create(item);
	}

	protected containsPrimitives() : boolean {
		return false;
	}

	protected containsIds() : boolean {
		return true;
	}

	protected createInstance(removeDestroyedItems : boolean) : ExportMembersExcelApiMemberIds<ValidationMode> {
		return new ExportMembersExcelApiMemberIds<ValidationMode>(this.api, removeDestroyedItems);
	}

	protected get dni() : string {
		return '2';
	}

	override createNewItem() : Id {
		const newItemRaw = null;

		const newItem = this.wrapItem(newItemRaw, true);
		this.push(newItem);

		if(this.api)
			this.api.changed('memberIds');

		return newItem;
	}

	override attributeInfoThis : ApiAttributeInfo<ExportMembersExcelApiMemberIds<ValidationMode>, ExportMembersExcelApiMemberIds<ValidationMode>> = new ApiAttributeInfo<ExportMembersExcelApiMemberIds<ValidationMode>, ExportMembersExcelApiMemberIds<ValidationMode>>({
			apiObjWrapper: this as any as ExportMembersExcelApiMemberIds<ValidationMode>,
			name: 'memberIds',
			id: 'MEMBER_IDS',
			primitiveType: PApiPrimitiveTypes.ApiList,
		});
	attributeInfoMemberId =  new ApiAttributeInfo<ExportMembersExcelApiMemberIds<ValidationMode>, Id>({
			apiObjWrapper: this as any as ExportMembersExcelApiMemberIds<ValidationMode>,
			name: 'memberId',
			id: 'MEMBER_ID',
			primitiveType: PApiPrimitiveTypes.Id,
		});
}

		

