import { Injectable, NgZone, Injector } from '@angular/core';
import { HttpClient, HttpParams, HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Router } from '@angular/router';
import { ApiBase, INITIALIZED_IN_BACKEND, NullableInDraftMode } from '@plano/shared/api/base/api-base';
import { Id } from '@plano/shared/api/base/id';
import { Meta } from '@plano/shared/api/base/meta';
import { ApiAttributeInfo } from '@plano/shared/api/base/api-attribute-info';
import { PApiPrimitiveTypes } from '@plano/shared/api/base/generated-types.ag';
import { ApiSaveArgs, ApiLoadArgs, ShiftId, ShiftSelector, ApiListWrapper, SchedulingApiPosSystem, SchedulingApiBooking, SchedulingApiAccountHolderState, ApiObjectWrapper, AuthenticatedApiRole } from '@plano/shared/api';
import { DateTime, Date, DateExclusiveEnd, LocalTime, Duration, Minutes, Hours, Days, Months, Years, Percent, Email, Search, Tel, Currency, Password, PostalCode, Integer, Url, Iban, Bic, Image } from '@plano/shared/api/base/generated-types.ag';
import { Config } from '@plano/shared/core/config';
import { AbstractControl } from '@angular/forms';
import { ApiErrorService } from '@plano/shared/api/api-error.service';



/**
 * This service enables access to the api "export_vouchers_boulderado_csv".
 * This file is auto generated by de.sage.scheduler.api_generator.ApiGenerator.
 */

// constants
class Consts
{
	VOUCHER_IDS = 1;
}


@Injectable({
  providedIn: 'root',
})
export class ExportVouchersBoulderadoCsvApiService<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiBase
{
	consts = new Consts();

	constructor(h : HttpClient
			,	router : Router
			,	apiE : ApiErrorService
			,	zone : NgZone
			,	injector : Injector) {
		super(h, router, apiE, zone, injector, 'export_vouchers_boulderado_csv');
	}

	protected version() : string {
		return 'd2457a29857e374d380160bbd69578ec,c34107733d4332e7baad6a58995e7d09';
	}

	private dataWrapper = new ExportVouchersBoulderadoCsvApiRoot<ValidationMode>(this);

	get data() : ExportVouchersBoulderadoCsvApiRoot<ValidationMode> {
		return this.dataWrapper;
	}

	protected getRootWrapper() : ExportVouchersBoulderadoCsvApiRoot<ValidationMode> {
		return this.dataWrapper;
	}

	protected recreateRootWrapper() : void {
		this.dataWrapper = new ExportVouchersBoulderadoCsvApiRoot<ValidationMode>(this);
	}
}

		 
export class ExportVouchersBoulderadoCsvApiRoot<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiObjectWrapper<any, any>
{
	

	constructor(override readonly api : ExportVouchersBoulderadoCsvApiService<ValidationMode> | null, idRaw : any = null) {
		super(api, ExportVouchersBoulderadoCsvApiRoot as any);

		this._updateRawData(Meta.createNewObject(false, idRaw), true);

		// set parent attribute
		this.voucherIdsWrapper.parent = this as any as ExportVouchersBoulderadoCsvApiRoot<ValidationMode>;
	}


	private _id : Id | null = null;
	get id() : Id {
		return this._id !== null ? this._id : Id.create(Meta.getNewItemId(this.rawData) as any);
	}

	override attributeInfoThis : ApiAttributeInfo<ExportVouchersBoulderadoCsvApiRoot<ValidationMode>, ExportVouchersBoulderadoCsvApiRoot<ValidationMode>> = new ApiAttributeInfo<ExportVouchersBoulderadoCsvApiRoot<ValidationMode>, ExportVouchersBoulderadoCsvApiRoot<ValidationMode>>({
			apiObjWrapper: this as any as ExportVouchersBoulderadoCsvApiRoot<ValidationMode>,
			name: '',
			id: 'ROOT',
			show: function(this : ExportVouchersBoulderadoCsvApiRoot<ValidationMode>) {
		if(!((this.api!.schedulingApi.data.posSystem === SchedulingApiPosSystem.BOULDERADO) &&( (this.api!.rightsService.requesterIs(AuthenticatedApiRole.CLIENT_OWNER))  || (this.api!.rightsService.requesterIs(AuthenticatedApiRole.ADMIN))  || (this.api!.rightsService.requesterIs(AuthenticatedApiRole.SUPER_ADMIN)) )))
		{
			return false;
		}
				return true;
			},
			canEdit: function(this : ExportVouchersBoulderadoCsvApiRoot<ValidationMode>) {
		if(!((this.api!.schedulingApi.data.posSystem === SchedulingApiPosSystem.BOULDERADO) &&( (this.api!.rightsService.requesterIs(AuthenticatedApiRole.CLIENT_OWNER))  || (this.api!.rightsService.requesterIs(AuthenticatedApiRole.ADMIN))  || (this.api!.rightsService.requesterIs(AuthenticatedApiRole.SUPER_ADMIN)) )))
		{
			return false;
		}
				return true;
			},
			readMode: function(this : ExportVouchersBoulderadoCsvApiRoot<ValidationMode>) {
						if(!(( (this.api!.rightsService.requesterIs(AuthenticatedApiRole.CLIENT_OWNER))  || (this.api!.rightsService.requesterIs(AuthenticatedApiRole.ADMIN))  || (this.api!.rightsService.requesterIs(AuthenticatedApiRole.SUPER_ADMIN)) )))
		{
			return true;
		}
				return false;
			},
		});

	private voucherIdsWrapper : ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode> = new ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>(this.api, false);

	/**
     *  Id list of the vouchers to be exported.
     */
	get voucherIds() : ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode> {
		return this.voucherIdsWrapper;
	}

	set voucherIdsTestSetter(v : ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>) {
        this.setterImpl(1, v.rawData, 'voucherIds', () => {this.voucherIdsWrapper = v;});
	}


	_fixIds(_idReplacements : Map<any, number>) : void {
		this.voucherIdsWrapper._fixIds(_idReplacements);
	}

	override _updateRawData(data : any[] | null, generateMissingData : boolean) : void {
		super._updateRawData(data, generateMissingData);

		this.data = data;

		// update id wrapper
		const idRawData = Meta.getId(data);
		this._id = idRawData === null ? null : Id.create(idRawData as any);

		// create missing/default data
		if(generateMissingData && data) {
			this.fillWithDefaultValues(data, 2);

			if(data[1] === null)
				data[1] = Meta.createNewList();
		}

		// propagate new raw data to children
		this.voucherIdsWrapper._updateRawData(data ? data[1] : null, generateMissingData);
	}

	protected get dni() : string {
		return '1';
	}

	static loadDetailed(	api : ExportVouchersBoulderadoCsvApiService<any>
						,	id : Id
						,	{success = null, error = null, searchParams = null} : ApiLoadArgs = {}) : Promise<HttpResponse<unknown>> {
		return ApiObjectWrapper.loadDetailedImpl(api, id, '1', { success: success, error: error, searchParams: searchParams});
	}

	protected assumeValidated() : asserts this is ExportVouchersBoulderadoCsvApiRoot<'validated'> {
		// TODO: PLANO-151346
	}
}

		 export class ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiListWrapper<any>
{
	override parent : any = null;

	constructor(override readonly api : ExportVouchersBoulderadoCsvApiService<ValidationMode> | null, removeDestroyedItems : boolean) {
		super(api, removeDestroyedItems, 'voucherIds');
	}

	override wrapItem(item : any, _generateMissingData : boolean) : ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode> {
		const newWrapper = new ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode>(this.api);
		newWrapper._updateRawData(item, _generateMissingData);
		return newWrapper;
	}

	protected containsPrimitives() : boolean {
		return false;
	}

	protected containsIds() : boolean {
		return false;
	}

	protected createInstance(removeDestroyedItems : boolean) : ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode> {
		return new ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>(this.api, removeDestroyedItems);
	}

	protected get dni() : string {
		return '2';
	}

	override createNewItem(id : Id | null = null) : ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode> {
		const newItemRaw = Meta.createNewObject(false, !!id ? id.rawData : null);

		const newItem = this.wrapItem(newItemRaw, true);
		this.push(newItem);

		if(this.api)
			this.api.changed('voucherIds');

		return newItem;
	}

	override attributeInfoThis : ApiAttributeInfo<ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>, ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>> = new ApiAttributeInfo<ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>, ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>>({
			apiObjWrapper: this as any as ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>,
			name: 'voucherIds',
			id: 'VOUCHER_IDS',
			primitiveType: PApiPrimitiveTypes.ApiList,
		});
	attributeInfoVoucherId =  new ApiAttributeInfo<ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>, ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode>>({
			apiObjWrapper: this as any as ExportVouchersBoulderadoCsvApiVoucherIds<ValidationMode>,
			name: 'voucherId',
			id: 'VOUCHER_ID',
		});
}

				 
export class ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiObjectWrapper<any, any>
{
	override parent : any = null;

	constructor(override readonly api : ExportVouchersBoulderadoCsvApiService<ValidationMode> | null, idRaw : any = null) {
		super(api, ExportVouchersBoulderadoCsvApiVoucherId as any);

		this._updateRawData(Meta.createNewObject(false, idRaw), true);

		// set parent attribute
	}


	private _id : Id | null = null;
	get id() : Id {
		return this._id !== null ? this._id : Id.create(Meta.getNewItemId(this.rawData) as any);
	}

	override attributeInfoThis : ApiAttributeInfo<ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode>, ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode>> = new ApiAttributeInfo<ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode>, ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode>>({
			apiObjWrapper: this as any as ExportVouchersBoulderadoCsvApiVoucherId<ValidationMode>,
			name: 'voucherId',
			id: 'VOUCHER_ID',
		});


	_fixIds(_idReplacements : Map<any, number>) : void {
	}

	override _updateRawData(data : any[] | null, generateMissingData : boolean) : void {
		super._updateRawData(data, generateMissingData);

		this.data = data;

		// update id wrapper
		const idRawData = Meta.getId(data);
		this._id = idRawData === null ? null : Id.create(idRawData as any);

		// create missing/default data
		if(generateMissingData && data) {
			this.fillWithDefaultValues(data, 1);

		}

		// propagate new raw data to children
	}

	protected get dni() : string {
		return '3';
	}

	static loadDetailed(	api : ExportVouchersBoulderadoCsvApiService<any>
						,	id : Id
						,	{success = null, error = null, searchParams = null} : ApiLoadArgs = {}) : Promise<HttpResponse<unknown>> {
		return ApiObjectWrapper.loadDetailedImpl(api, id, '3', { success: success, error: error, searchParams: searchParams});
	}

	protected assumeValidated() : asserts this is ExportVouchersBoulderadoCsvApiVoucherId<'validated'> {
		// TODO: PLANO-151346
	}
}



