import { Injectable, NgZone, Injector } from '@angular/core';
import { HttpClient, HttpParams, HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Router } from '@angular/router';
import { ApiBase, INITIALIZED_IN_BACKEND, NullableInDraftMode } from '@plano/shared/api/base/api-base';
import { Id } from '@plano/shared/api/base/id';
import { Meta } from '@plano/shared/api/base/meta';
import { ApiAttributeInfo } from '@plano/shared/api/base/api-attribute-info';
import { PApiPrimitiveTypes } from '@plano/shared/api/base/generated-types.ag';
import { ApiSaveArgs, ApiLoadArgs, ShiftId, ShiftSelector, ApiListWrapper, SchedulingApiPosSystem, SchedulingApiBooking, SchedulingApiAccountHolderState, ApiObjectWrapper, AuthenticatedApiRole } from '@plano/shared/api';
import { DateTime, Date, DateExclusiveEnd, LocalTime, Duration, Minutes, Hours, Days, Months, Years, Percent, Email, Search, Tel, Currency, Password, PostalCode, Integer, Url, Iban, Bic, Image } from '@plano/shared/api/base/generated-types.ag';
import { Config } from '@plano/shared/core/config';
import { AbstractControl } from '@angular/forms';
import { ApiErrorService } from '@plano/shared/api/api-error.service';



/**
 * This service enables access to the api "export_bookings_excel".
 * This file is auto generated by de.sage.scheduler.api_generator.ApiGenerator.
 */

// constants
class Consts
{
	BOOKING_IDS = 1;
	SHIFT_MODEL_IDS = 2;
}


@Injectable({
  providedIn: 'root',
})
export class ExportBookingsExcelApiService<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiBase
{
	consts = new Consts();

	constructor(h : HttpClient
			,	router : Router
			,	apiE : ApiErrorService
			,	zone : NgZone
			,	injector : Injector) {
		super(h, router, apiE, zone, injector, 'export_bookings_excel');
	}

	protected version() : string {
		return 'f33a5c3c66e66b01b4488f391f2a3efc,ea44a6700b1f2b9a163740ed4d6dc56a';
	}

	private dataWrapper = new ExportBookingsExcelApiRoot<ValidationMode>(this);

	get data() : ExportBookingsExcelApiRoot<ValidationMode> {
		return this.dataWrapper;
	}

	protected getRootWrapper() : ExportBookingsExcelApiRoot<ValidationMode> {
		return this.dataWrapper;
	}

	protected recreateRootWrapper() : void {
		this.dataWrapper = new ExportBookingsExcelApiRoot<ValidationMode>(this);
	}
}

		 
export class ExportBookingsExcelApiRoot<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiObjectWrapper<any, any>
{
	

	constructor(override readonly api : ExportBookingsExcelApiService<ValidationMode> | null, idRaw : any = null) {
		super(api, ExportBookingsExcelApiRoot as any);

		this._updateRawData(Meta.createNewObject(false, idRaw), true);

		// set parent attribute
		this.bookingIdsWrapper.parent = this as any as ExportBookingsExcelApiRoot<ValidationMode>;
		this.shiftModelIdsWrapper.parent = this as any as ExportBookingsExcelApiRoot<ValidationMode>;
	}


	private _id : Id | null = null;
	get id() : Id {
		return this._id !== null ? this._id : Id.create(Meta.getNewItemId(this.rawData) as any);
	}

	override attributeInfoThis : ApiAttributeInfo<ExportBookingsExcelApiRoot<ValidationMode>, ExportBookingsExcelApiRoot<ValidationMode>> = new ApiAttributeInfo<ExportBookingsExcelApiRoot<ValidationMode>, ExportBookingsExcelApiRoot<ValidationMode>>({
			apiObjWrapper: this as any as ExportBookingsExcelApiRoot<ValidationMode>,
			name: '',
			id: 'ROOT',
			show: function(this : ExportBookingsExcelApiRoot<ValidationMode>) {
		if(!((this.api!.rightsService.hasManagerRights)))
		{
			return false;
		}
				return true;
			},
			canEdit: function(this : ExportBookingsExcelApiRoot<ValidationMode>) {
		if(!((this.api!.rightsService.hasManagerRights)))
		{
			return false;
		}
				return true;
			},
			readMode: function(this : ExportBookingsExcelApiRoot<ValidationMode>) {
				 
		
				return false;
			},
		});

	private bookingIdsWrapper : ExportBookingsExcelApiBookingIds<ValidationMode> = new ExportBookingsExcelApiBookingIds<ValidationMode>(this.api, false);

	/**
     *  Id list of the bookings to be exported.
     */
	get bookingIds() : ExportBookingsExcelApiBookingIds<ValidationMode> {
		return this.bookingIdsWrapper;
	}

	set bookingIdsTestSetter(v : ExportBookingsExcelApiBookingIds<ValidationMode>) {
        this.setterImpl(1, v.rawData, 'bookingIds', () => {this.bookingIdsWrapper = v;});
	}

	private shiftModelIdsWrapper : ExportBookingsExcelApiShiftModelIds<ValidationMode> = new ExportBookingsExcelApiShiftModelIds<ValidationMode>(this.api, false);

	/**
     *  Id list of the shift model to be exported.
     */
	get shiftModelIds() : ExportBookingsExcelApiShiftModelIds<ValidationMode> {
		return this.shiftModelIdsWrapper;
	}

	set shiftModelIdsTestSetter(v : ExportBookingsExcelApiShiftModelIds<ValidationMode>) {
        this.setterImpl(2, v.rawData, 'shiftModelIds', () => {this.shiftModelIdsWrapper = v;});
	}


	_fixIds(_idReplacements : Map<any, number>) : void {
		this.bookingIdsWrapper._fixIds(_idReplacements);
		this.shiftModelIdsWrapper._fixIds(_idReplacements);
	}

	override _updateRawData(data : any[] | null, generateMissingData : boolean) : void {
		super._updateRawData(data, generateMissingData);

		this.data = data;

		// update id wrapper
		const idRawData = Meta.getId(data);
		this._id = idRawData === null ? null : Id.create(idRawData as any);

		// create missing/default data
		if(generateMissingData && data) {
			this.fillWithDefaultValues(data, 3);

			if(data[1] === null)
				data[1] = Meta.createNewList();
			if(data[2] === null)
				data[2] = Meta.createNewList();
		}

		// propagate new raw data to children
		this.bookingIdsWrapper._updateRawData(data ? data[1] : null, generateMissingData);
		this.shiftModelIdsWrapper._updateRawData(data ? data[2] : null, generateMissingData);
	}

	protected get dni() : string {
		return '1';
	}

	static loadDetailed(	api : ExportBookingsExcelApiService<any>
						,	id : Id
						,	{success = null, error = null, searchParams = null} : ApiLoadArgs = {}) : Promise<HttpResponse<unknown>> {
		return ApiObjectWrapper.loadDetailedImpl(api, id, '1', { success: success, error: error, searchParams: searchParams});
	}

	protected assumeValidated() : asserts this is ExportBookingsExcelApiRoot<'validated'> {
		// TODO: PLANO-151346
	}
}

		 export class ExportBookingsExcelApiBookingIds<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiListWrapper<any>
{
	override parent : any = null;

	constructor(override readonly api : ExportBookingsExcelApiService<ValidationMode> | null, removeDestroyedItems : boolean) {
		super(api, removeDestroyedItems, 'bookingIds');
	}

	override wrapItem(item : any, _generateMissingData : boolean) : ExportBookingsExcelApiBookingId<ValidationMode> {
		const newWrapper = new ExportBookingsExcelApiBookingId<ValidationMode>(this.api);
		newWrapper._updateRawData(item, _generateMissingData);
		return newWrapper;
	}

	protected containsPrimitives() : boolean {
		return false;
	}

	protected containsIds() : boolean {
		return false;
	}

	protected createInstance(removeDestroyedItems : boolean) : ExportBookingsExcelApiBookingIds<ValidationMode> {
		return new ExportBookingsExcelApiBookingIds<ValidationMode>(this.api, removeDestroyedItems);
	}

	protected get dni() : string {
		return '2';
	}

	override createNewItem(id : Id | null = null) : ExportBookingsExcelApiBookingId<ValidationMode> {
		const newItemRaw = Meta.createNewObject(false, !!id ? id.rawData : null);

		const newItem = this.wrapItem(newItemRaw, true);
		this.push(newItem);

		if(this.api)
			this.api.changed('bookingIds');

		return newItem;
	}

	override attributeInfoThis : ApiAttributeInfo<ExportBookingsExcelApiBookingIds<ValidationMode>, ExportBookingsExcelApiBookingIds<ValidationMode>> = new ApiAttributeInfo<ExportBookingsExcelApiBookingIds<ValidationMode>, ExportBookingsExcelApiBookingIds<ValidationMode>>({
			apiObjWrapper: this as any as ExportBookingsExcelApiBookingIds<ValidationMode>,
			name: 'bookingIds',
			id: 'BOOKING_IDS',
			primitiveType: PApiPrimitiveTypes.ApiList,
		});
	attributeInfoBookingId =  new ApiAttributeInfo<ExportBookingsExcelApiBookingIds<ValidationMode>, ExportBookingsExcelApiBookingId<ValidationMode>>({
			apiObjWrapper: this as any as ExportBookingsExcelApiBookingIds<ValidationMode>,
			name: 'bookingId',
			id: 'BOOKING_ID',
		});
}

				 
export class ExportBookingsExcelApiBookingId<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiObjectWrapper<any, any>
{
	override parent : any = null;

	constructor(override readonly api : ExportBookingsExcelApiService<ValidationMode> | null, idRaw : any = null) {
		super(api, ExportBookingsExcelApiBookingId as any);

		this._updateRawData(Meta.createNewObject(false, idRaw), true);

		// set parent attribute
	}


	private _id : Id | null = null;
	get id() : Id {
		return this._id !== null ? this._id : Id.create(Meta.getNewItemId(this.rawData) as any);
	}

	override attributeInfoThis : ApiAttributeInfo<ExportBookingsExcelApiBookingId<ValidationMode>, ExportBookingsExcelApiBookingId<ValidationMode>> = new ApiAttributeInfo<ExportBookingsExcelApiBookingId<ValidationMode>, ExportBookingsExcelApiBookingId<ValidationMode>>({
			apiObjWrapper: this as any as ExportBookingsExcelApiBookingId<ValidationMode>,
			name: 'bookingId',
			id: 'BOOKING_ID',
		});


	_fixIds(_idReplacements : Map<any, number>) : void {
	}

	override _updateRawData(data : any[] | null, generateMissingData : boolean) : void {
		super._updateRawData(data, generateMissingData);

		this.data = data;

		// update id wrapper
		const idRawData = Meta.getId(data);
		this._id = idRawData === null ? null : Id.create(idRawData as any);

		// create missing/default data
		if(generateMissingData && data) {
			this.fillWithDefaultValues(data, 1);

		}

		// propagate new raw data to children
	}

	protected get dni() : string {
		return '4';
	}

	static loadDetailed(	api : ExportBookingsExcelApiService<any>
						,	id : Id
						,	{success = null, error = null, searchParams = null} : ApiLoadArgs = {}) : Promise<HttpResponse<unknown>> {
		return ApiObjectWrapper.loadDetailedImpl(api, id, '4', { success: success, error: error, searchParams: searchParams});
	}

	protected assumeValidated() : asserts this is ExportBookingsExcelApiBookingId<'validated'> {
		// TODO: PLANO-151346
	}
}

		 export class ExportBookingsExcelApiShiftModelIds<ValidationMode extends 'draft' | 'validated' = 'validated'> extends ApiListWrapper<any>
{
	override parent : any = null;

	constructor(override readonly api : ExportBookingsExcelApiService<ValidationMode> | null, removeDestroyedItems : boolean) {
		super(api, removeDestroyedItems, 'shiftModelIds');
	}

	override wrapItem(item : any, _generateMissingData : boolean) : Id {
		return Id.create(item);
	}

	protected containsPrimitives() : boolean {
		return false;
	}

	protected containsIds() : boolean {
		return true;
	}

	protected createInstance(removeDestroyedItems : boolean) : ExportBookingsExcelApiShiftModelIds<ValidationMode> {
		return new ExportBookingsExcelApiShiftModelIds<ValidationMode>(this.api, removeDestroyedItems);
	}

	protected get dni() : string {
		return '3';
	}

	override createNewItem() : Id {
		const newItemRaw = null;

		const newItem = this.wrapItem(newItemRaw, true);
		this.push(newItem);

		if(this.api)
			this.api.changed('shiftModelIds');

		return newItem;
	}

	override attributeInfoThis : ApiAttributeInfo<ExportBookingsExcelApiShiftModelIds<ValidationMode>, ExportBookingsExcelApiShiftModelIds<ValidationMode>> = new ApiAttributeInfo<ExportBookingsExcelApiShiftModelIds<ValidationMode>, ExportBookingsExcelApiShiftModelIds<ValidationMode>>({
			apiObjWrapper: this as any as ExportBookingsExcelApiShiftModelIds<ValidationMode>,
			name: 'shiftModelIds',
			id: 'SHIFT_MODEL_IDS',
			primitiveType: PApiPrimitiveTypes.ApiList,
		});
	attributeInfoShiftModelId =  new ApiAttributeInfo<ExportBookingsExcelApiShiftModelIds<ValidationMode>, Id>({
			apiObjWrapper: this as any as ExportBookingsExcelApiShiftModelIds<ValidationMode>,
			name: 'shiftModelId',
			id: 'SHIFT_MODEL_ID',
			primitiveType: PApiPrimitiveTypes.Id,
		});
}

		

