/**
 * ATTENTION: This file is auto generated by de.sage.scheduler.api_generator.ApiGenerator.
 */

/**
 * The api files have heavy circular dependencies. To ensure correct import order we use this index.ts file
 * to provide the correct import order here. We must ensure that in code the api files are never imported
 * directly but only by importing this file.
 *
 * For details see: https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de
 */

/**
 * First export all classes which are used as base classes.
 */
export * from './base/api-base';
export * from './base/api-data-wrapper-base';
export * from './base/api-list-wrapper';
export * from './base/api-lists';
export * from './base/api-object-wrapper';
export * from './base/meta';
export * from './base/types';

export * from './account-api/account-api.service.ag';
export * from './affected-shifts-api/affected-shifts-api.service.ag';
export * from './authenticated-api/authenticated-api.service.ag';
export * from './booking-system-data-api/booking-system-data-api.service.ag';
export * from './clients-api/clients-api.service.ag';
export * from './email-valid-api/email-valid-api.service.ag';
export * from './export-billing-data-api/export-billing-data-api.service.ag';
export * from './export-bookings-excel-api/export-bookings-excel-api.service.ag';
export * from './export-course-statistics-excel-api/export-course-statistics-excel-api.service.ag';
export * from './export-members-excel-api/export-members-excel-api.service.ag';
export * from './export-reporting-excel-api/export-reporting-excel-api.service.ag';
export * from './export-shift-exchange-statistics-excel-api/export-shift-exchange-statistics-excel-api.service.ag';
export * from './export-shifts-excel-api/export-shifts-excel-api.service.ag';
export * from './export-transactions-excel-api/export-transactions-excel-api.service.ag';
export * from './export-vouchers-boulderado-csv-api/export-vouchers-boulderado-csv-api.service.ag';
export * from './export-vouchers-excel-api/export-vouchers-excel-api.service.ag';
export * from './failed-adyen-events-api/failed-adyen-events-api.service.ag';
export * from './forgot-password-api/forgot-password-api.service.ag';
export * from './ical-api/ical-api.service.ag';
export * from './register-test-account-api/register-test-account-api.service.ag';
export * from './scheduling-api/scheduling-api.service.ag';
export * from './server-timer-api/server-timer-api.service.ag';
export * from './state-machines-api/state-machines-api.service.ag';
export * from './story-book-api/story-book-api.service.ag';
export * from './subscribe-newsletter-api/subscribe-newsletter-api.service.ag';
export * from './test-data-api/test-data-api.service.ag';
export * from './time-stamp-api/time-stamp-api.service.ag';
export * from './verify-test-account-api/verify-test-account-api.service.ag';

/**
 * Now export all sub-classes.
 */
export * from '@plano/shared/api/scheduling-api/shift-id/shift-selector';
export * from '@plano/shared/api/scheduling-api/shift-id/shift-id';
export * from '@plano/shared/core/me/me.service';

export * from '@plano/client/account/api/account-api.service';
export * from '@plano/client/shared/api/affected-shifts-api.service';
export * from '@plano/shared/core/authenticated-api.service';
export * from '@plano/admin/clients-api/clients-api.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-working-time.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-shift-exchange.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-assignment-process.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-booking.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-shiftmodel-course.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-shift-model-cancellation-policy.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-transactions.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-warning.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-adyen-account.service';
export * from '@plano/client/scheduling/shared/api/scheduling-api-mail-sent-to-booking-person.service';
export * from '@plano/client/time-stamp/time-stamp-api.service';

/**
 * Export misc classes.
 */
export * from './scheduling-api/shift-exchange-concept.service.ag';
export * from '@plano/client/accesscontrol/rights.service';

/**
 * Export array of api providers.
 */
import { ApiErrorService } from './api-error.service';

import { AccountApiService } from '@plano/shared/api';
import { AffectedShiftsApiService } from '@plano/shared/api';
import { AuthenticatedApiService } from '@plano/shared/api';
import { BookingSystemDataApiService } from '@plano/shared/api';
import { ClientsApiService } from '@plano/shared/api';
import { EmailValidApiService } from '@plano/shared/api';
import { ExportBillingDataApiService } from '@plano/shared/api';
import { ExportBookingsExcelApiService } from '@plano/shared/api';
import { ExportCourseStatisticsExcelApiService } from '@plano/shared/api';
import { ExportMembersExcelApiService } from '@plano/shared/api';
import { ExportReportingExcelApiService } from '@plano/shared/api';
import { ExportShiftExchangeStatisticsExcelApiService } from '@plano/shared/api';
import { ExportShiftsExcelApiService } from '@plano/shared/api';
import { ExportTransactionsExcelApiService } from '@plano/shared/api';
import { ExportVouchersBoulderadoCsvApiService } from '@plano/shared/api';
import { ExportVouchersExcelApiService } from '@plano/shared/api';
import { FailedAdyenEventsApiService } from '@plano/shared/api';
import { ForgotPasswordApiService } from '@plano/shared/api';
import { IcalApiService } from '@plano/shared/api';
import { RegisterTestAccountApiService } from '@plano/shared/api';
import { SchedulingApiService } from '@plano/shared/api';
import { ServerTimerApiService } from '@plano/shared/api';
import { StateMachinesApiService } from '@plano/shared/api';
import { StoryBookApiService } from '@plano/shared/api';
import { SubscribeNewsletterApiService } from '@plano/shared/api';
import { TestDataApiService } from '@plano/shared/api';
import { TimeStampApiService } from '@plano/shared/api';
import { VerifyTestAccountApiService } from '@plano/shared/api';

